apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    purpose: verify-file-private-endpoint  
spec:
  containers:
    - name: test-container
      image: busybox
      command:
        - sleep
        - "3600"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    purpose: web-server
    app: nginx  
spec:
  containers:
    - name: http-server
      image: nginx
      ports:
        - containerPort: 80
          name: "server"
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: nginx
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx