---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  skuName: $SKU_NAME
  resourceGroup: $RESOURCE_GROUP
  storageAccount: $STORAGE_ACCOUNT_NAME
  shareName: $SHARE_NAME
  secretName: $STORAGE_SECRET_NAME
  secretNamespace: $STORAGE_SECRET_NAMESPACE
  server: $STORAGE_ACCOUNT_NAME.privatelink.file.core.windows.net
  protocol: nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true