# https://play.openpolicyagent.org/p/ikesWCFIH8
# https://docs.microsoft.com/en-us/azure/governance/policy/samples/built-in-policies#kubernetes
apiVersion: v1
kind: Pod
metadata:
  name: dark-registry-malware
spec:
  containers:
  - name:  dark-registry-malware
    image:  hub.dark-registry.grd/hacked-image:wip
    command: ['sh', '-c', 'while true;do date;echo hello;sleep 10;done']
    resources:
      requests:
        memory: "12Mi"
        cpu: "100m"
      limits:
        memory: "20Mi"
        cpu: "100m"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /tmp/
  volumes:
  - name: workdir
    emptyDir: {}