---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  skuName: Premium_LRS
  resourceGroup: rg-azarc-aro-francecentral
  storageAccount: stfrfileazarc
  shareName: arofs
  secretName: azure-storage-secret
  secretNamespace: default
  server: stfrfileazarc.privatelink.file.core.windows.net
  protocol: nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true